use docker

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,59 +1,46 @@
-dist: trusty
-sudo: required
-language: c
-cache:
-  apt: true
-  directories:
-  - $HOME/.opam
-addons:
-  apt:
-    sources:
-    - avsm
-    packages:
-    - opam
-    - aspcud
+os: linux
+dist: bionic
+language: shell
+
+services:
+  - docker
+
 env:
   global:
-  - NJOBS=2
-  # system is == 4.02.3
-  - COMPILER="4.07.1"
-  # Main test targets
-  matrix:
-  - TEST_TARGET="v8.11"
-  - TEST_TARGET="v8.12"
-  - TEST_TARGET="master"
+  - NJOBS="2"
+  - PACKAGE_NAME="coq-color"
+  jobs:
+  - COQ_IMAGE="coqorg/coq:8.11"
+  - COQ_IMAGE="coqorg/coq:8.12"
+  - COQ_IMAGE="coqorg/coq:dev"
 
-install:
-# Opam
-- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
-- eval $(opam config env)
-- opam config var root
-- opam list
-- opam install -y -j ${NJOBS} ocamlfind camlp5 ${EXTRA_OPAM}
-- opam install -y -j ${NJOBS} num zarith
-# Coq
-- echo 'Installing Coq...' && echo -en 'travis_fold:start:coq.build\\r'
-- git clone --depth 1 -b ${TEST_TARGET} https://github.com/coq/coq.git ${HOME}/coq-${TEST_TARGET}
-- cd ${HOME}/coq-${TEST_TARGET}
-- ./configure -native-compiler no -local -coqide no
-- make -j ${NJOBS}
-- cd -
-- echo -en 'travis_fold:end:coq.build\\r'
-# BigNums
-- echo 'Installing BigNums...' && echo -en 'travis_fold:start:bign.build\\r'
-- export PATH=${HOME}/coq-${TEST_TARGET}/bin:$PATH
-- git clone --depth 1 -b ${TEST_TARGET} https://github.com/coq/bignums.git ${HOME}/bign-${TEST_TARGET}
-- cd ${HOME}/bign-${TEST_TARGET}
-- make -j ${NJOBS} && make install
-- cd -
-- echo -en 'travis_fold:end:bign.build\\r'
+install: |
+  # Prepare the COQ container
+  docker pull ${COQ_IMAGE}
+  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${PACKAGE_NAME} -w /home/coq/${PACKAGE_NAME} ${COQ_IMAGE}
+  docker exec COQ /bin/bash --login -c "
+    # This bash script is double-quoted to interpolate Travis CI env vars:
+    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex  # -e = exit on failure; -x = trace for debug
+    opam update -y
+    opam pin add ${PACKAGE_NAME} . --kind=path --no-action -y
+    opam config list; opam repo list; opam pin list; opam list
+    " install
 
 script:
-- echo 'Building CoLoR...' && echo -en 'travis_fold:start:color.build\\r'
-- export PATH=${HOME}/coq-${TEST_TARGET}/bin:$PATH
-- make -j ${NJOBS}
-- echo -en 'travis_fold:end:color.build\\r'
+- echo -e "${ANSI_YELLOW}Building ${PACKAGE_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
+- |
+  docker exec COQ /bin/bash --login -c "
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
+    sudo chown -R coq:coq /home/coq/${PACKAGE_NAME}
+    # First install the dependencies
+    opam install ${PACKAGE_NAME} --deps-only -y
+    opam list
+    # Then install the package itself in verbose mode
+    opam install ${PACKAGE_NAME} -v -y
+    " script
+- echo -en 'travis_fold:end:script\\r'
 
-notifications:
-  email:
-    - frederic.blanqui@inria.fr
+after_script:
+- docker stop COQ  # optional but recommended
